/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupPasswordRouteImport } from './routes/setup-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWorkforceRouteImport } from './routes/_authenticated/workforce'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDailyWorkMattersRouteImport } from './routes/_authenticated/daily-work-matters'
import { Route as AuthenticatedQuantifyIndexRouteImport } from './routes/_authenticated/quantify/index'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminInvitationsRouteImport } from './routes/_authenticated/admin/invitations'
import { Route as AuthenticatedAdminDwmRouteImport } from './routes/_authenticated/admin/dwm'
import { Route as ApiPublicHooksWeeklyDwmReportRouteImport } from './routes/api/public/hooks/weekly-dwm-report'

const SetupPasswordRoute = SetupPasswordRouteImport.update({
  id: '/setup-password',
  path: '/setup-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkforceRoute = AuthenticatedWorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDailyWorkMattersRoute =
  AuthenticatedDailyWorkMattersRouteImport.update({
    id: '/daily-work-matters',
    path: '/daily-work-matters',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQuantifyIndexRoute =
  AuthenticatedQuantifyIndexRouteImport.update({
    id: '/quantify/',
    path: '/quantify/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminInvitationsRoute =
  AuthenticatedAdminInvitationsRouteImport.update({
    id: '/admin/invitations',
    path: '/admin/invitations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDwmRoute = AuthenticatedAdminDwmRouteImport.update({
  id: '/admin/dwm',
  path: '/admin/dwm',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicHooksWeeklyDwmReportRoute =
  ApiPublicHooksWeeklyDwmReportRouteImport.update({
    id: '/api/public/hooks/weekly-dwm-report',
    path: '/api/public/hooks/weekly-dwm-report',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup-password': typeof SetupPasswordRoute
  '/daily-work-matters': typeof AuthenticatedDailyWorkMattersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/workforce': typeof AuthenticatedWorkforceRoute
  '/admin/dwm': typeof AuthenticatedAdminDwmRoute
  '/admin/invitations': typeof AuthenticatedAdminInvitationsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/quantify/': typeof AuthenticatedQuantifyIndexRoute
  '/api/public/hooks/weekly-dwm-report': typeof ApiPublicHooksWeeklyDwmReportRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup-password': typeof SetupPasswordRoute
  '/daily-work-matters': typeof AuthenticatedDailyWorkMattersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/workforce': typeof AuthenticatedWorkforceRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/dwm': typeof AuthenticatedAdminDwmRoute
  '/admin/invitations': typeof AuthenticatedAdminInvitationsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/quantify': typeof AuthenticatedQuantifyIndexRoute
  '/api/public/hooks/weekly-dwm-report': typeof ApiPublicHooksWeeklyDwmReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup-password': typeof SetupPasswordRoute
  '/_authenticated/daily-work-matters': typeof AuthenticatedDailyWorkMattersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/workforce': typeof AuthenticatedWorkforceRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/dwm': typeof AuthenticatedAdminDwmRoute
  '/_authenticated/admin/invitations': typeof AuthenticatedAdminInvitationsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/quantify/': typeof AuthenticatedQuantifyIndexRoute
  '/api/public/hooks/weekly-dwm-report': typeof ApiPublicHooksWeeklyDwmReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/setup-password'
    | '/daily-work-matters'
    | '/settings'
    | '/workforce'
    | '/admin/dwm'
    | '/admin/invitations'
    | '/admin/users'
    | '/quantify/'
    | '/api/public/hooks/weekly-dwm-report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/reset-password'
    | '/setup-password'
    | '/daily-work-matters'
    | '/settings'
    | '/workforce'
    | '/'
    | '/admin/dwm'
    | '/admin/invitations'
    | '/admin/users'
    | '/quantify'
    | '/api/public/hooks/weekly-dwm-report'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/setup-password'
    | '/_authenticated/daily-work-matters'
    | '/_authenticated/settings'
    | '/_authenticated/workforce'
    | '/_authenticated/'
    | '/_authenticated/admin/dwm'
    | '/_authenticated/admin/invitations'
    | '/_authenticated/admin/users'
    | '/_authenticated/quantify/'
    | '/api/public/hooks/weekly-dwm-report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupPasswordRoute: typeof SetupPasswordRoute
  ApiPublicHooksWeeklyDwmReportRoute: typeof ApiPublicHooksWeeklyDwmReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup-password': {
      id: '/setup-password'
      path: '/setup-password'
      fullPath: '/setup-password'
      preLoaderRoute: typeof SetupPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workforce': {
      id: '/_authenticated/workforce'
      path: '/workforce'
      fullPath: '/workforce'
      preLoaderRoute: typeof AuthenticatedWorkforceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daily-work-matters': {
      id: '/_authenticated/daily-work-matters'
      path: '/daily-work-matters'
      fullPath: '/daily-work-matters'
      preLoaderRoute: typeof AuthenticatedDailyWorkMattersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quantify/': {
      id: '/_authenticated/quantify/'
      path: '/quantify'
      fullPath: '/quantify/'
      preLoaderRoute: typeof AuthenticatedQuantifyIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/invitations': {
      id: '/_authenticated/admin/invitations'
      path: '/admin/invitations'
      fullPath: '/admin/invitations'
      preLoaderRoute: typeof AuthenticatedAdminInvitationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/dwm': {
      id: '/_authenticated/admin/dwm'
      path: '/admin/dwm'
      fullPath: '/admin/dwm'
      preLoaderRoute: typeof AuthenticatedAdminDwmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hooks/weekly-dwm-report': {
      id: '/api/public/hooks/weekly-dwm-report'
      path: '/api/public/hooks/weekly-dwm-report'
      fullPath: '/api/public/hooks/weekly-dwm-report'
      preLoaderRoute: typeof ApiPublicHooksWeeklyDwmReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDailyWorkMattersRoute: typeof AuthenticatedDailyWorkMattersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWorkforceRoute: typeof AuthenticatedWorkforceRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminDwmRoute: typeof AuthenticatedAdminDwmRoute
  AuthenticatedAdminInvitationsRoute: typeof AuthenticatedAdminInvitationsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedQuantifyIndexRoute: typeof AuthenticatedQuantifyIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDailyWorkMattersRoute: AuthenticatedDailyWorkMattersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWorkforceRoute: AuthenticatedWorkforceRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminDwmRoute: AuthenticatedAdminDwmRoute,
  AuthenticatedAdminInvitationsRoute: AuthenticatedAdminInvitationsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedQuantifyIndexRoute: AuthenticatedQuantifyIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupPasswordRoute: SetupPasswordRoute,
  ApiPublicHooksWeeklyDwmReportRoute: ApiPublicHooksWeeklyDwmReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
